export const CONFIG_CONSTANT = {
  HEADER_PRIMARY_COLOR: "HEADER.PRIMARY_COLOR",
  HEADER_LOGO: "HEADER_LOGO",
  HEADER_COMMUNITY_NAME: "HEADER_COMMUNITY_NAME",
  HERO_TAG_DATA_ONE: "HERO_TAG_DATA_ONE",
  HERO_TAG_DATA_TWO: "HERO_TAG_DATA_TWO",
  HERO_TAG_DATA_THREE: "HERO_TAG_DATA_THREE",
  HERO_IMAGE_URL: "HERO_IMAGE_URL",
  HERO_MAIN_TEXT: "HERO_MAIN_TEXT",
  HERO_SUB_TEXT: "HERO_SUB_TEXT",
  HIGHLIGHT_BOX_TEXT: "HIGHLIGHT_TEXT_BOX_TEXT",
  HIGHLIGHT_BOX_BG_COLOR: "HIGHLIGHT_BOX_BG_COLOR",
};
