export const CONFIG_CONSTANT = {
  HEADER_PRIMARY_COLOR: "HEADER.PRIMARY_COLOR",
  HEADER_LOGO: "HEADER_LOGO",
  HEADER_COMMUNITY_NAME: "HEADER_COMMUNITY_NAME",

  /////////
  HERO_TAG_DATA_ONE: "HERO_TAG_DATA_ONE",
  HERO_TAG_DATA_TWO: "HERO_TAG_DATA_TWO",
  HERO_TAG_DATA_THREE: "HERO_TAG_DATA_THREE",
  HERO_IMAGE_URL: "HERO_IMAGE_URL",
  HERO_MAIN_TEXT: "HERO_MAIN_TEXT",
  HERO_SUB_TEXT: "HERO_SUB_TEXT",
  HIGHLIGHT_BOX_TEXT: "HIGHLIGHT_TEXT_BOX_TEXT",
  HIGHLIGHT_BOX_BG_COLOR: "HIGHLIGHT_BOX_BG_COLOR",

  ///////
  ABOUT_US_DESCRIPTION: "ABOUT_US_DESCRIPTION",
  ABOUT_US_TAG_ONE: "ABOUT_US_TAG_ONE",
  ABOUT_US_TAG_TWO: "ABOUT_US_TAG_TWO",
  ABOUT_US_TAG_THREE: "ABOUT_US_TAG_THREE",
  ABOUT_US_TAG_FOUR: "ABOUT_US_TAG_FOUR",
  ABOUT_US_TAG_FIVE: "ABOUT_US_TAG_FIVE",

  //////
  MEMBER_DATA: "MEMBER_DATA",

  EVENTS_DATA: "EVENTS_DATA",
  // EVENT_DESCRIPTION: "EVENT_DESCRIPTION",
  // EVENT_DATE: "EVENT_DATE",
  // EVENT_PLACE: "EVENT_PLACE",
  // EVENT_PARTICIPANTS: "EVENT_PARTICIPANTS",
  // EVENT_JOINING_LINK: "EVENT_JOINING_LINK",
  // EVENT_STATUS: "EVENT_STATUS",
  ////////////
};
